# Generated by Django 4.2.3 on 2023-08-12 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 12, 14, 43, 35, 72042, tzinfo=datetime.timezone.utc)),
        ),
    ]
